### ISSUE TITLE
Collections Users

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#165] opened 2015-12-14 03:03 UTC
We need to have the capability of assigning users to a specific collection (it does not matter whether the collection is *private* or *public*). The group of users should be able to add or delete files to a collection. The deletion process should move deleted files to a trash folder that can only be emptied by a super user of the editing group. This is an *essential* functionality when creating a data set collaboratively.

**Comment by slhowes** [comment] 2015-12-15 06:46
We talked about this in Monday's meeting. This is not actually an issue.

**Comment by musicus** [comment] 2015-12-15 12:45
:-)

**Comment by musicus** [comment] 2015-12-15 13:03
This is not marked as a bug, just as an enhancement, and no we cannot assign a group of users to work on a specific data set. By it being public anybody with an account can work on the data set, and I'm not sure if that is desirable. Public or non public is not granular enough.

**Comment by lexpar** [comment] 2016-01-13 17:19
Duplicate of #167

**Closed by lexpar** 2016-01-13 17:19 UTC
Labels: enhancement
