### ISSUE TITLE
Downloading pieces

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvis-database#195] opened 2016-02-15 18:55 UTC
When downloading pieces the following question comes up: _Most pieces have multiple file formats associated with them. Which formats would you like to download?_ It is not clear that the file formats need to be click-selected from the drop-down menu. Also, the _All files_ default leads the user to believe that nothing else needs to happen/be selected in order to download, but when the download button is pushed nothing happens (clearly this is happening because nothing was selected, but it is non-intuitive). A more common usability practice or "pattern" for this procedure should be implemented.

**Comment by lexpar** [comment] 2016-02-15 19:18
*Something* should be happening when you click the download button in that case. The intended behavior is that leaving the drop down on the 'all files' default will put all the files into the zip. 

This is actually a bug with the download views, which makes sense since I'm in the process of refactoring them,  and it's likely something broke without me noticing.

**Comment by lexpar** [comment] 2016-02-15 19:20
I would recommend to Andrew that he let this bug stay where it is for now--there's more refactoring to do, and fixing it now might not necessarily be helpful if more changed are coming over the next couple days.

**Comment by AFFogarty** [comment] 2016-02-16 15:47
So far as the GUI is concerned, I think that it would be best to render a list of checkboxes corresponding to the available file extensions.

The user could check or uncheck the file extensions that they would like to download.

**Comment by AFFogarty** [comment] 2016-02-16 20:28
Ok, here is my mockup:

![downloading](https://cloud.githubusercontent.com/assets/2154530/13090108/e8900f36-d4c1-11e5-9194-14d202d6e137.PNG)

**Comment by musicus** [comment] 2016-02-16 20:34
:facepunch: :+1:

**Comment by AFFogarty** [comment] 2016-02-16 20:40
I went ahead and built some GUI components for #176.
![directories_mockup](https://cloud.githubusercontent.com/assets/2154530/13090425/95adb96a-d4c3-11e5-8236-0d5a19154013.PNG)

**Comment by musicus** [comment] 2016-02-16 20:41
:neckbeard: :+1:

**Comment by AFFogarty** [comment] 2016-02-16 21:56
Ok, I've committed the code in de9db72.  Going to mark this as fixed.

**Closed by AFFogarty** 2016-02-16 21:56 UTC
Labels: Priority: LOW, Status: IN PROGRESS, Type: USABILITY, Version: DEV

**Comment by musicus** [comment] 2016-02-16 21:59
:100:
